#!/bin/bash

PYFILE="$1"

if [ ! -f "$PYFILE" ]; then

    echo "$PYFILE: No such file or directory" >&2

        exit 1

        fi

        OUTFILE="$PYFILE""c"

        python3 -m compileall "$PYFILE"

        if [ -f "$OUTFILE" ]; then

            echo "Compiling $PYFILE ..."

        else

            echo "Compilation of $PYFILE failed" >&2

                exit 1

                fi
